-- ─── Vocabulary bank ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS vocabulary_bank (
  id            SERIAL      PRIMARY KEY,
  word          TEXT        NOT NULL UNIQUE,
  cluster_id    INTEGER     NOT NULL REFERENCES clusters(id) ON DELETE CASCADE,
  core_meaning  TEXT        NOT NULL,
  usage_example TEXT        NOT NULL,
  alternatives  JSONB       NOT NULL DEFAULT '[]',
  difficulty    INTEGER     NOT NULL CHECK (difficulty BETWEEN 1 AND 5),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ─── Expand session log ───────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS expand_session_log (
  id           SERIAL      PRIMARY KEY,
  user_id      UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  cluster_id   INTEGER     NOT NULL REFERENCES clusters(id),
  words_shown  JSONB       NOT NULL DEFAULT '[]',
  completed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ─── Vocabulary bank generation log ──────────────────────────────────────────

CREATE TABLE IF NOT EXISTS vocabulary_bank_generation_log (
  id           SERIAL      PRIMARY KEY,
  cluster_id   INTEGER     NOT NULL REFERENCES clusters(id),
  words_added  INTEGER     NOT NULL,
  triggered_by TEXT        NOT NULL CHECK (triggered_by IN ('cron', 'manual')),
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ─── Seed: 20 words per cluster (140 total) ───────────────────────────────────
-- Words already in onboarding_words are excluded.

INSERT INTO vocabulary_bank (word, cluster_id, core_meaning, usage_example, alternatives, difficulty) VALUES

-- ── professional (20) ────────────────────────────────────────────────────────
('adept',
  (SELECT id FROM clusters WHERE name='professional'),
  'Naturally skilled at something through practice or experience.',
  'She is adept at managing competing priorities without losing sight of the overall goal.',
  '["skilled", "capable", "competent"]', 1),

('decisive',
  (SELECT id FROM clusters WHERE name='professional'),
  'Able to make clear choices quickly and with confidence.',
  'His decisive call on the vendor dispute avoided a week of unnecessary back-and-forth.',
  '["firm", "resolute", "clear"]', 1),

('resourceful',
  (SELECT id FROM clusters WHERE name='professional'),
  'Skilled at finding practical solutions with limited means.',
  'The resourceful analyst built the entire report without any budget for new tools.',
  '["inventive", "capable", "practical"]', 2),

('accountable',
  (SELECT id FROM clusters WHERE name='professional'),
  'Willing to take responsibility for the outcomes of your actions.',
  'Staying accountable to deadlines is what builds trust on a team over time.',
  '["responsible", "answerable", "reliable"]', 1),

('proactive',
  (SELECT id FROM clusters WHERE name='professional'),
  'Taking action before problems arise rather than waiting to react.',
  'She proactively flagged the compliance risk before it ever reached the client.',
  '["forward-thinking", "preventive", "initiative-driven"]', 1),

('rigorous',
  (SELECT id FROM clusters WHERE name='professional'),
  'Careful, thorough, and exacting in your standards.',
  'The audit was rigorous, examining every line of the financial report for inconsistencies.',
  '["thorough", "strict", "demanding"]', 2),

('scalable',
  (SELECT id FROM clusters WHERE name='professional'),
  'Able to grow in capacity without losing quality or efficiency.',
  'They chose a scalable infrastructure that could handle sudden spikes in user traffic.',
  '["expandable", "flexible", "adaptable"]', 2),

('cohesive',
  (SELECT id FROM clusters WHERE name='professional'),
  'Working together as a unified and effective whole.',
  'A cohesive team consistently outperforms a group of talented individuals working in silos.',
  '["unified", "aligned", "integrated"]', 2),

('benchmark',
  (SELECT id FROM clusters WHERE name='professional'),
  'A standard used to measure or compare quality, performance, or value.',
  'The company benchmarks its response times against the top performers in the industry.',
  '["standard", "measure", "reference point"]', 2),

('robust',
  (SELECT id FROM clusters WHERE name='professional'),
  'Strong, reliable, and unlikely to fail under pressure.',
  'The robust system handled three times the expected load without a single error.',
  '["strong", "reliable", "solid"]', 1),

('iterative',
  (SELECT id FROM clusters WHERE name='professional'),
  'Improving through repeated cycles of testing and refinement.',
  'The iterative design process meant each version was measurably better than the last.',
  '["incremental", "cyclical", "step-by-step"]', 3),

('viable',
  (SELECT id FROM clusters WHERE name='professional'),
  'Capable of working successfully in practice.',
  'Only two of the five proposed approaches were financially viable given the timeline.',
  '["feasible", "workable", "realistic"]', 1),

('forthright',
  (SELECT id FROM clusters WHERE name='professional'),
  'Direct and outspoken in sharing your views without being asked.',
  'Being forthright about delays builds more trust than letting clients be surprised.',
  '["direct", "frank", "honest"]', 2),

('seamless',
  (SELECT id FROM clusters WHERE name='professional'),
  'Smooth and without interruption or visible effort.',
  'The handover between teams was seamless — the client barely noticed the transition.',
  '["smooth", "effortless", "uninterrupted"]', 1),

('leverage',
  (SELECT id FROM clusters WHERE name='professional'),
  'Use something effectively to gain an advantage or achieve a result.',
  'They leveraged existing partnerships to accelerate the product launch by two months.',
  '["use", "apply", "exploit"]', 2),

('contingency',
  (SELECT id FROM clusters WHERE name='professional'),
  'A provision made for a possible future event or problem.',
  'Every launch plan should include a contingency in case the primary approach fails.',
  '["backup", "fallback", "precaution"]', 3),

('deft',
  (SELECT id FROM clusters WHERE name='professional'),
  'Showing skill and cleverness, especially under pressure.',
  'She handled the difficult stakeholder question with deft precision and no defensiveness.',
  '["nimble", "skillful", "adroit"]', 2),

('streamlined',
  (SELECT id FROM clusters WHERE name='professional'),
  'Made more efficient by removing unnecessary steps or complexity.',
  'After the redesign, the approval process was streamlined from twelve steps to three.',
  '["simplified", "efficient", "optimised"]', 2),

('deliverable',
  (SELECT id FROM clusters WHERE name='professional'),
  'A specific, measurable output that can be completed and handed over.',
  'Define your deliverables clearly before the kickoff so expectations are aligned from day one.',
  '["output", "result", "product"]', 1),

('aligned',
  (SELECT id FROM clusters WHERE name='professional'),
  'In agreement or working toward the same goal.',
  'Make sure all stakeholders are aligned before moving from planning to execution.',
  '["agreed", "coordinated", "on the same page"]', 1),

-- ── expression (20) ──────────────────────────────────────────────────────────
('resonant',
  (SELECT id FROM clusters WHERE name='expression'),
  'Having a quality that feels meaningful and stays with the listener.',
  'Her closing remarks were resonant, drawing on stories that everyone in the room could relate to.',
  '["meaningful", "striking", "memorable"]', 2),

('poignant',
  (SELECT id FROM clusters WHERE name='expression'),
  'Evoking a strong sense of meaning, often tinged with longing or emotion.',
  'The final scene was poignant — simple, quiet, and difficult to shake for days afterward.',
  '["moving", "touching", "affecting"]', 2),

('stirring',
  (SELECT id FROM clusters WHERE name='expression'),
  'Causing strong feelings of excitement, admiration, or emotion.',
  'It was a stirring speech that left the audience on their feet and the room buzzing.',
  '["rousing", "moving", "inspiring"]', 2),

('lyrical',
  (SELECT id FROM clusters WHERE name='expression'),
  'Expressing emotion in a beautiful, flowing way that feels close to poetry.',
  'Her prose was lyrical without being overdone — every sentence earned its rhythm.',
  '["melodic", "poetic", "flowing"]', 2),

('arresting',
  (SELECT id FROM clusters WHERE name='expression'),
  'So striking or unexpected that it stops you and demands your attention.',
  'The opening image in the essay was arresting — a single sentence that reframed everything that followed.',
  '["striking", "captivating", "gripping"]', 3),

('fluent',
  (SELECT id FROM clusters WHERE name='expression'),
  'Able to express thoughts smoothly and without noticeable effort.',
  'She was fluent in three languages and equally fluent in the language of persuasion.',
  '["smooth", "natural", "effortless"]', 1),

('terse',
  (SELECT id FROM clusters WHERE name='expression'),
  'Brief and to the point, sometimes to the point of seeming clipped.',
  'His terse reply made it clear the topic was not up for further discussion.',
  '["brief", "clipped", "blunt"]', 2),

('trenchant',
  (SELECT id FROM clusters WHERE name='expression'),
  'Presenting ideas with force, clarity, and unsettling precision.',
  'The trenchant editorial dissected the policy''s flaws in under five paragraphs.',
  '["sharp", "incisive", "forceful"]', 4),

('understated',
  (SELECT id FROM clusters WHERE name='expression'),
  'Deliberately restrained in a way that creates more impact, not less.',
  'Her delivery was understated, which made the final line hit far harder than a dramatic reading would have.',
  '["subtle", "restrained", "controlled"]', 3),

('measured',
  (SELECT id FROM clusters WHERE name='expression'),
  'Carefully considered and precise rather than rushed or excessive.',
  'She gave a measured response that acknowledged the criticism without conceding the core point.',
  '["careful", "considered", "deliberate"]', 2),

('pithy',
  (SELECT id FROM clusters WHERE name='expression'),
  'Short but packed with meaning and force.',
  'A pithy one-liner can land harder than a full paragraph of careful explanation.',
  '["concise", "punchy", "crisp"]', 3),

('polished',
  (SELECT id FROM clusters WHERE name='expression'),
  'Refined and impressive in execution, with nothing rough around the edges.',
  'The final presentation was polished — clean slides, crisp delivery, and a strong close.',
  '["refined", "smooth", "accomplished"]', 2),

('cogent',
  (SELECT id FROM clusters WHERE name='expression'),
  'Clear, logical, and genuinely convincing in argument.',
  'The case he made was cogent enough that even the sharpest critics conceded the main point.',
  '["convincing", "logical", "well-reasoned"]', 3),

('adroit',
  (SELECT id FROM clusters WHERE name='expression'),
  'Clever and skilful, especially in handling a difficult situation with words.',
  'She was adroit at shifting the tone of a difficult conversation without making it obvious.',
  '["skilled", "nimble", "deft"]', 3),

('apt',
  (SELECT id FROM clusters WHERE name='expression'),
  'Exactly right or appropriate for the situation or point being made.',
  'He chose an apt metaphor that everyone in the room understood immediately.',
  '["fitting", "suitable", "well-chosen"]', 1),

('animated',
  (SELECT id FROM clusters WHERE name='expression'),
  'Full of life and energy in the way you speak or describe something.',
  'Her animated delivery kept the room engaged for the entire two-hour session.',
  '["lively", "energetic", "expressive"]', 1),

('limpid',
  (SELECT id FROM clusters WHERE name='expression'),
  'Perfectly clear and easy to understand, with nothing clouding the meaning.',
  'The instructions were limpid — three steps, no jargon, no ambiguity.',
  '["clear", "transparent", "plain"]', 4),

('incisive',
  (SELECT id FROM clusters WHERE name='expression'),
  'Sharp, direct, and getting straight to the heart of the matter.',
  'Her incisive analysis cut through the noise and landed on the real issue in two sentences.',
  '["sharp", "direct", "acute"]', 2),

('spirited',
  (SELECT id FROM clusters WHERE name='expression'),
  'Full of energy, enthusiasm, and conviction in what you say.',
  'The spirited debate continued well past the scheduled end time, with no sign of letting up.',
  '["energetic", "lively", "passionate"]', 1),

('vivacious',
  (SELECT id FROM clusters WHERE name='expression'),
  'Attractively lively and animated in personality and the way you communicate.',
  'Her vivacious storytelling turned a dry case study into something the audience actually wanted to hear.',
  '["lively", "vibrant", "dynamic"]', 3),

-- ── thinking (20) ────────────────────────────────────────────────────────────
('systematic',
  (SELECT id FROM clusters WHERE name='thinking'),
  'Done according to a careful and organized plan, leaving nothing to chance.',
  'A systematic approach to debugging saves far more time than guessing at the cause.',
  '["organised", "structured", "thorough"]', 1),

('deliberate',
  (SELECT id FROM clusters WHERE name='thinking'),
  'Done consciously, carefully, and with full awareness of the implications.',
  'His deliberate word choices showed he had thought through every possible interpretation.',
  '["intentional", "considered", "careful"]', 2),

('shrewd',
  (SELECT id FROM clusters WHERE name='thinking'),
  'Having sharp judgment and clever, practical understanding of a situation.',
  'A shrewd negotiator knows that silence often accomplishes more than another argument.',
  '["sharp", "clever", "canny"]', 2),

('sound',
  (SELECT id FROM clusters WHERE name='thinking'),
  'Based on solid reasoning and reliable evidence, with no logical gaps.',
  'Her argument was sound — every claim was supported and every assumption was stated.',
  '["solid", "logical", "valid"]', 1),

('calibrated',
  (SELECT id FROM clusters WHERE name='thinking'),
  'Adjusted carefully to match the actual level or complexity of a situation.',
  'His response was calibrated — firm enough to register, restrained enough not to escalate.',
  '["adjusted", "measured", "tuned"]', 3),

('deductive',
  (SELECT id FROM clusters WHERE name='thinking'),
  'Using logical reasoning from general principles to reach specific conclusions.',
  'His deductive approach worked through the problem step by methodical step until only one answer remained.',
  '["logical", "reasoned", "inferential"]', 3),

('lateral',
  (SELECT id FROM clusters WHERE name='thinking'),
  'Thinking in creative or unconventional ways that bypass the obvious path.',
  'The solution came from lateral thinking — no one had considered approaching it from that angle before.',
  '["creative", "sideways", "unconventional"]', 2),

('circumspect',
  (SELECT id FROM clusters WHERE name='thinking'),
  'Wary and careful, thinking through consequences before acting.',
  'She was circumspect about making promises she had no way to be certain of keeping.',
  '["careful", "cautious", "guarded"]', 3),

('empirical',
  (SELECT id FROM clusters WHERE name='thinking'),
  'Based on observation and real-world evidence rather than theory alone.',
  'His empirical approach meant every claim in the report was backed by data, not assumption.',
  '["evidence-based", "observational", "practical"]', 3),

('skeptical',
  (SELECT id FROM clusters WHERE name='thinking'),
  'Not easily convinced and inclined to question claims before accepting them.',
  'She was appropriately skeptical of the optimistic projections in the first-quarter report.',
  '["questioning", "doubtful", "critical"]', 2),

('exacting',
  (SELECT id FROM clusters WHERE name='thinking'),
  'Demanding high standards of accuracy and effort from yourself or others.',
  'Her exacting review caught three errors everyone else had missed in multiple read-throughs.',
  '["demanding", "precise", "strict"]', 3),

('grounded',
  (SELECT id FROM clusters WHERE name='thinking'),
  'Sensible and stable in your thinking, not carried away by extremes.',
  'Staying grounded under pressure means not catastrophizing before you know the full picture.',
  '["stable", "balanced", "sensible"]', 1),

('probing',
  (SELECT id FROM clusters WHERE name='thinking'),
  'Asking questions that go beneath the surface to reveal what''s really there.',
  'Her probing questions revealed assumptions the team had been carrying for months without examining.',
  '["searching", "deep", "investigative"]', 2),

('logical',
  (SELECT id FROM clusters WHERE name='thinking'),
  'Following the rules of clear, valid reasoning without contradiction.',
  'The logical structure of his argument made it difficult for critics to find a foothold.',
  '["reasoned", "coherent", "valid"]', 1),

('structured',
  (SELECT id FROM clusters WHERE name='thinking'),
  'Organized in a clear, planned way that makes the thinking easy to follow.',
  'A structured approach to the problem helped them avoid revisiting the same dead ends.',
  '["organized", "planned", "ordered"]', 1),

('insightful',
  (SELECT id FROM clusters WHERE name='thinking'),
  'Showing a deep and accurate understanding that others haven''t yet reached.',
  'Her insightful observation reframed the entire discussion and changed what the team decided to build.',
  '["perceptive", "keen", "astute"]', 2),

('impartial',
  (SELECT id FROM clusters WHERE name='thinking'),
  'Not influenced by personal feelings or bias when forming a view.',
  'An impartial review requires setting aside what you hoped the data would show.',
  '["neutral", "unbiased", "fair"]', 2),

('hypothetical',
  (SELECT id FROM clusters WHERE name='thinking'),
  'Based on a proposed scenario rather than established facts.',
  'Walk through the hypothetical: what would happen if the primary system failed mid-launch?',
  '["theoretical", "speculative", "assumed"]', 3),

('exhaustive',
  (SELECT id FROM clusters WHERE name='thinking'),
  'Covering every possible case or angle, leaving nothing unconsidered.',
  'An exhaustive analysis doesn''t just answer the question — it surfaces the questions you didn''t think to ask.',
  '["thorough", "comprehensive", "complete"]', 3),

('disciplined',
  (SELECT id FROM clusters WHERE name='thinking'),
  'Controlled and orderly in your thinking, staying focused on what matters.',
  'Disciplined thinking means staying with hard questions long enough to find real answers.',
  '["focused", "controlled", "rigorous"]', 2),

-- ── character (20) ────────────────────────────────────────────────────────────
('integrity',
  (SELECT id FROM clusters WHERE name='character'),
  'Doing what''s right even when no one is watching or when it costs you something.',
  'Integrity means your behavior is the same whether or not anyone is checking.',
  '["honesty", "ethics", "principle"]', 1),

('gritty',
  (SELECT id FROM clusters WHERE name='character'),
  'Having courage and determination that holds up under real difficulty.',
  'The gritty determination she showed in the final quarter inspired everyone around her.',
  '["tough", "determined", "persistent"]', 1),

('humble',
  (SELECT id FROM clusters WHERE name='character'),
  'Having a realistic view of your own importance and willing to learn from others.',
  'He was humble enough to admit the plan had serious flaws, which made the team trust him far more.',
  '["modest", "unassuming", "grounded"]', 1),

('authentic',
  (SELECT id FROM clusters WHERE name='character'),
  'Genuinely being yourself rather than performing a version of who you think you should be.',
  'People respond to authentic leaders because they can sense when the performance ends.',
  '["genuine", "real", "honest"]', 1),

('introspective',
  (SELECT id FROM clusters WHERE name='character'),
  'Given to examining your own thoughts, feelings, and motivations carefully.',
  'Becoming introspective after a setback is the first step toward actually growing from it.',
  '["self-examining", "reflective", "thoughtful"]', 3),

('resolute',
  (SELECT id FROM clusters WHERE name='character'),
  'Firmly determined to achieve something and not giving up when it gets hard.',
  'She was resolute in her refusal to compromise on the project''s core values, even under pressure.',
  '["determined", "unwavering", "firm"]', 2),

('gracious',
  (SELECT id FROM clusters WHERE name='character'),
  'Courteous and kind, especially in situations where you don''t have to be.',
  'He was gracious in defeat, congratulating the other team without a trace of bitterness.',
  '["kind", "polite", "generous"]', 2),

('stoic',
  (SELECT id FROM clusters WHERE name='character'),
  'Enduring difficulty without complaint or visible emotional reaction.',
  'His stoic response to the setback stopped the panic from spreading through the rest of the team.',
  '["unflinching", "patient", "enduring"]', 2),

('earnest',
  (SELECT id FROM clusters WHERE name='character'),
  'Serious and sincere in your intentions and effort.',
  'Her earnest attempt to understand the client''s concerns changed the tone of the entire meeting.',
  '["sincere", "genuine", "wholehearted"]', 1),

('unflappable',
  (SELECT id FROM clusters WHERE name='character'),
  'Calm in a crisis and not easily rattled by unexpected problems.',
  'The unflappable project manager kept the team focused when the system failed mid-demo.',
  '["calm", "steady", "unfazed"]', 3),

('scrupulous',
  (SELECT id FROM clusters WHERE name='character'),
  'Very careful to act with honesty and avoid anything ethically questionable.',
  'A scrupulous editor checks every claim before publishing, even when the source seems reliable.',
  '["careful", "thorough", "principled"]', 3),

('forthcoming',
  (SELECT id FROM clusters WHERE name='character'),
  'Willing to share information openly and readily without being pressed.',
  'The forthcoming response from leadership helped contain the team''s anxiety before it spread.',
  '["open", "direct", "candid"]', 2),

('conscientious',
  (SELECT id FROM clusters WHERE name='character'),
  'Very careful about doing your work thoroughly and correctly.',
  'She''s conscientious about every detail, which means her work rarely needs a second pass.',
  '["careful", "diligent", "thorough"]', 2),

('adaptable',
  (SELECT id FROM clusters WHERE name='character'),
  'Able to adjust to new situations or challenges without losing effectiveness.',
  'In a fast-changing industry, being adaptable matters more than having the right experience.',
  '["flexible", "versatile", "adjustable"]', 1),

('persistent',
  (SELECT id FROM clusters WHERE name='character'),
  'Continuing to try even after facing setbacks or repeated obstacles.',
  'Persistent effort over months achieved what no single sprint could.',
  '["determined", "dogged", "consistent"]', 1),

('wholehearted',
  (SELECT id FROM clusters WHERE name='character'),
  'Showing complete sincerity and commitment without reservation.',
  'Her wholehearted support for the initiative gave the rest of the team the confidence to try.',
  '["total", "committed", "unreserved"]', 2),

('credible',
  (SELECT id FROM clusters WHERE name='character'),
  'Trusted and believed by others because of consistent honesty and reliability.',
  'She built a credible reputation by admitting mistakes early rather than trying to conceal them.',
  '["trustworthy", "believable", "reliable"]', 2),

('balanced',
  (SELECT id FROM clusters WHERE name='character'),
  'Keeping different priorities or perspectives in a sensible, fair proportion.',
  'A balanced approach weighs both short-term results and what they cost in the long run.',
  '["even", "measured", "proportionate"]', 1),

('committed',
  (SELECT id FROM clusters WHERE name='character'),
  'Having a strong sense of dedication to a task, person, or cause.',
  'Committed people don''t wait to be told — they see what needs doing and they do it.',
  '["dedicated", "devoted", "loyal"]', 1),

('magnanimous',
  (SELECT id FROM clusters WHERE name='character'),
  'Generous and forgiving toward someone who has wronged you or competed against you.',
  'His magnanimous response to the criticism earned him far more respect than a sharp reply would have.',
  '["generous", "forgiving", "big-hearted"]', 4),

-- ── communication (20) ───────────────────────────────────────────────────────
('direct',
  (SELECT id FROM clusters WHERE name='communication'),
  'Saying exactly what you mean without unnecessary hedging or softening.',
  'Be direct about timelines — vague answers create false expectations that come back to haunt you.',
  '["straightforward", "plain", "frank"]', 1),

('explicit',
  (SELECT id FROM clusters WHERE name='communication'),
  'Leaving nothing to implication; very clear and detailed about what you mean.',
  'The contract needs to be explicit about who owns the intellectual property from day one.',
  '["clear", "specific", "unambiguous"]', 2),

('conciliatory',
  (SELECT id FROM clusters WHERE name='communication'),
  'Trying to reduce conflict by taking a friendly, accommodating approach.',
  'Her conciliatory tone helped defuse what had been a tense and unproductive exchange.',
  '["accommodating", "peacemaking", "soothing"]', 3),

('tactful',
  (SELECT id FROM clusters WHERE name='communication'),
  'Able to say difficult things in a way that doesn''t unnecessarily upset people.',
  'Being tactful doesn''t mean avoiding the truth — it means delivering it with care.',
  '["sensitive", "considerate", "thoughtful"]', 2),

('unequivocal',
  (SELECT id FROM clusters WHERE name='communication'),
  'Leaving no room for doubt or misinterpretation; completely clear.',
  'His unequivocal rejection of the proposal ended the discussion immediately.',
  '["clear", "unmistakable", "absolute"]', 3),

('frank',
  (SELECT id FROM clusters WHERE name='communication'),
  'Honest and direct, sometimes in a way that catches people off guard.',
  'She was frank about the budget shortfall rather than dancing around the uncomfortable reality.',
  '["direct", "honest", "candid"]', 1),

('communicative',
  (SELECT id FROM clusters WHERE name='communication'),
  'Willing and able to share information and ideas clearly and openly.',
  'A communicative manager prevents the information gaps that slow entire teams down.',
  '["open", "sharing", "transparent"]', 1),

('accessible',
  (SELECT id FROM clusters WHERE name='communication'),
  'Easy to understand by a wide range of people, not just specialists.',
  'Keep technical explanations accessible — not everyone in the room knows the jargon.',
  '["clear", "understandable", "approachable"]', 1),

('engaging',
  (SELECT id FROM clusters WHERE name='communication'),
  'Holding people''s attention and making them want to keep listening.',
  'An engaging presenter makes even complex data feel like something worth paying attention to.',
  '["captivating", "interesting", "involving"]', 1),

('convincing',
  (SELECT id FROM clusters WHERE name='communication'),
  'Making someone believe something through clear evidence or well-constructed argument.',
  'The proposal was convincing enough to get sign-off in a single meeting.',
  '["persuasive", "credible", "compelling"]', 2),

('disarming',
  (SELECT id FROM clusters WHERE name='communication'),
  'Unexpectedly reducing hostility or suspicion with warmth or honesty.',
  'His disarming humility caught the critics off guard and changed the energy in the room.',
  '["charming", "reassuring", "unexpected"]', 3),

('impactful',
  (SELECT id FROM clusters WHERE name='communication'),
  'Having a strong and noticeable effect on the people hearing it.',
  'The most impactful messages are often the simplest: one sentence, two numbers, one ask.',
  '["powerful", "effective", "striking"]', 2),

('authoritative',
  (SELECT id FROM clusters WHERE name='communication'),
  'Carrying weight and credibility because it is backed by knowledge and confidence.',
  'An authoritative voice doesn''t need to shout — it carries because people trust what''s behind it.',
  '["confident", "commanding", "credible"]', 2),

('specific',
  (SELECT id FROM clusters WHERE name='communication'),
  'Exact and particular about what you mean, leaving no room for guessing.',
  'Specific feedback — not "needs work" but exactly what needs work — is what actually helps people improve.',
  '["exact", "precise", "detailed"]', 1),

('intentional',
  (SELECT id FROM clusters WHERE name='communication'),
  'Done with clear purpose and thought about the effect on the listener.',
  'Intentional communication means asking what you want the person to walk away believing.',
  '["purposeful", "considered", "mindful"]', 2),

('attuned',
  (SELECT id FROM clusters WHERE name='communication'),
  'Aware and sensitive to the feelings, needs, or mood of others in a conversation.',
  'An attuned communicator adjusts their tone before the other person has to ask.',
  '["sensitive", "aware", "tuned-in"]', 3),

('clear',
  (SELECT id FROM clusters WHERE name='communication'),
  'Easy to understand with no ambiguity or unnecessary complexity.',
  'Clear communication saves more time than any process improvement you could put in place.',
  '["plain", "straightforward", "unambiguous"]', 1),

('upfront',
  (SELECT id FROM clusters WHERE name='communication'),
  'Honest about relevant things at the start rather than waiting to be asked.',
  'Being upfront about delays early gives people time to adjust their plans, not just their expectations.',
  '["honest", "direct", "open"]', 1),

('responsive',
  (SELECT id FROM clusters WHERE name='communication'),
  'Quick to react to questions, requests, or changing needs.',
  'A responsive communicator doesn''t leave people wondering where things stand.',
  '["attentive", "prompt", "reactive"]', 2),

('open',
  (SELECT id FROM clusters WHERE name='communication'),
  'Sharing information freely and genuinely willing to hear other views.',
  'Leaders who are open to feedback create teams that aren''t afraid to speak up.',
  '["transparent", "honest", "approachable"]', 1),

-- ── emotional (20) ───────────────────────────────────────────────────────────
('vulnerable',
  (SELECT id FROM clusters WHERE name='emotional'),
  'Willing to show and acknowledge your own feelings and uncertainties.',
  'Being vulnerable in a meeting takes courage but often changes the entire dynamic for the better.',
  '["open", "exposed", "unguarded"]', 2),

('compassionate',
  (SELECT id FROM clusters WHERE name='emotional'),
  'Feeling and showing genuine care for others who are struggling.',
  'A compassionate response acknowledges what''s hard before it offers any kind of solution.',
  '["caring", "sympathetic", "understanding"]', 2),

('buoyant',
  (SELECT id FROM clusters WHERE name='emotional'),
  'Cheerful and resilient, especially under conditions that would bring others down.',
  'Her buoyant attitude during the crunch kept morale from collapsing when it easily could have.',
  '["upbeat", "optimistic", "resilient"]', 3),

('centered',
  (SELECT id FROM clusters WHERE name='emotional'),
  'Calm and sure of your own values and reactions, not thrown off by outside pressure.',
  'Staying centered in a heated argument means responding from what you believe, not from your ego.',
  '["calm", "balanced", "steady"]', 2),

('attentive',
  (SELECT id FROM clusters WHERE name='emotional'),
  'Paying close and genuine attention to what others need or are feeling.',
  'An attentive person asks questions rather than rushing to offer a solution.',
  '["alert", "considerate", "focused"]', 1),

('temperate',
  (SELECT id FROM clusters WHERE name='emotional'),
  'Showing moderation and self-restraint rather than giving in to strong emotions.',
  'A temperate response is far harder to dismiss or argue against than an emotional one.',
  '["moderate", "calm", "restrained"]', 3),

('sentimental',
  (SELECT id FROM clusters WHERE name='emotional'),
  'Strongly influenced by feelings and personal memories rather than logic alone.',
  'She made a sentimental decision to keep the handwritten notes rather than scanning and discarding them.',
  '["nostalgic", "emotional", "feeling-driven"]', 2),

('serene',
  (SELECT id FROM clusters WHERE name='emotional'),
  'Calm and untroubled, even in situations that would stress most people.',
  'She remained serene throughout the audit, which unsettled the critics who had expected defensiveness.',
  '["calm", "peaceful", "tranquil"]', 2),

('emotive',
  (SELECT id FROM clusters WHERE name='emotional'),
  'Arousing or conveying strong feelings in others.',
  'The emotive appeal at the end of the presentation moved several board members to change their vote.',
  '["emotional", "moving", "feeling-driven"]', 2),

('heartfelt',
  (SELECT id FROM clusters WHERE name='emotional'),
  'Expressing a deep and genuine feeling that comes across as sincere.',
  'A heartfelt apology does more than a formal one because it names what was actually lost.',
  '["sincere", "warm", "genuine"]', 1),

('intuitive',
  (SELECT id FROM clusters WHERE name='emotional'),
  'Relying on instinct and inner feeling rather than only conscious analysis.',
  'Her intuitive read of the room shifted the conversation at exactly the moment it needed to shift.',
  '["instinctive", "perceptive", "feeling-based"]', 2),

('optimistic',
  (SELECT id FROM clusters WHERE name='emotional'),
  'Hopeful and confident about the future, even when things are uncertain.',
  'Staying optimistic in uncertainty doesn''t mean ignoring risks — it means not being defeated by them.',
  '["hopeful", "positive", "encouraged"]', 1),

('durable',
  (SELECT id FROM clusters WHERE name='emotional'),
  'Able to withstand difficult conditions over time without breaking down.',
  'Building a durable sense of self means not letting every criticism reshape your identity.',
  '["lasting", "strong", "enduring"]', 2),

('curious',
  (SELECT id FROM clusters WHERE name='emotional'),
  'Genuinely eager to understand something rather than assuming you already do.',
  'Stay curious about how others are feeling — it makes conversations far richer than assumptions do.',
  '["interested", "eager", "open-minded"]', 1),

('generous',
  (SELECT id FROM clusters WHERE name='emotional'),
  'Willing to give more of your time, energy, or praise than strictly required.',
  'Being generous with recognition costs nothing and builds enormous goodwill over time.',
  '["giving", "open-handed", "kind"]', 1),

('wary',
  (SELECT id FROM clusters WHERE name='emotional'),
  'Cautious because of a realistic sense that something could go wrong.',
  'She was wary of the sudden enthusiasm, having watched it fizzle too many times before.',
  '["cautious", "guarded", "careful"]', 2),

('conflicted',
  (SELECT id FROM clusters WHERE name='emotional'),
  'Experiencing opposing emotions or pulls at the same time.',
  'He felt conflicted about leaving a role he loved for one that paid significantly more.',
  '["torn", "ambivalent", "divided"]', 2),

('sensitive',
  (SELECT id FROM clusters WHERE name='emotional'),
  'Aware of and responsive to the feelings and needs of others.',
  'A sensitive approach to delivering difficult news helps people process it rather than shut down.',
  '["aware", "careful", "thoughtful"]', 1),

('collected',
  (SELECT id FROM clusters WHERE name='emotional'),
  'Calm and in full control of your emotions even when things are going badly.',
  'She appeared collected during the presentation, though she had been anxious all morning.',
  '["calm", "composed", "unflustered"]', 2),

('tender',
  (SELECT id FROM clusters WHERE name='emotional'),
  'Gentle and warm in a way that shows genuine care for someone else.',
  'A tender response can disarm anger that a sharp reply would only reinforce.',
  '["gentle", "warm", "soft"]', 2),

-- ── interpersonal (20) ───────────────────────────────────────────────────────
('trustworthy',
  (SELECT id FROM clusters WHERE name='interpersonal'),
  'Reliably honest and dependable in ways others can count on.',
  'Being trustworthy is not a reputation you claim — it''s one others assign to you over time.',
  '["dependable", "reliable", "honest"]', 1),

('approachable',
  (SELECT id FROM clusters WHERE name='interpersonal'),
  'Easy and comfortable to talk to, without making people feel they''re intruding.',
  'An approachable manager hears about problems before they have time to become crises.',
  '["friendly", "accessible", "open"]', 1),

('inclusive',
  (SELECT id FROM clusters WHERE name='interpersonal'),
  'Making sure everyone feels welcome and considered, not just the loudest voices.',
  'Inclusive meetings start by actively creating space for the people who don''t naturally speak first.',
  '["welcoming", "open", "broad"]', 2),

('rapport',
  (SELECT id FROM clusters WHERE name='interpersonal'),
  'A close, harmonious relationship in which people understand and trust each other.',
  'Building rapport with a client takes time but makes every conversation that follows faster and easier.',
  '["connection", "trust", "bond"]', 2),

('mindful',
  (SELECT id FROM clusters WHERE name='interpersonal'),
  'Aware of how your words and actions land on other people.',
  'Being mindful of tone makes difficult messages much easier for the other person to actually receive.',
  '["aware", "thoughtful", "considerate"]', 2),

('convivial',
  (SELECT id FROM clusters WHERE name='interpersonal'),
  'Friendly and lively in a way that puts others at ease in social situations.',
  'His convivial nature made him the natural choice to lead the team''s onboarding lunch.',
  '["sociable", "warm", "genial"]', 3),

('reliable',
  (SELECT id FROM clusters WHERE name='interpersonal'),
  'Consistently doing what you say you''ll do, when you said you''d do it.',
  'Reliable people don''t just deliver results — they deliver at the expected time, every time.',
  '["dependable", "consistent", "steady"]', 1),

('considerate',
  (SELECT id FROM clusters WHERE name='interpersonal'),
  'Thinking about other people''s feelings and needs before you act.',
  'A considerate colleague checks in rather than assuming someone is fine.',
  '["thoughtful", "caring", "kind"]', 1),

('gregarious',
  (SELECT id FROM clusters WHERE name='interpersonal'),
  'Finding energy and enjoyment in the company of others.',
  'The gregarious team lead set a tone that made even the quieter introverts want to participate.',
  '["sociable", "outgoing", "friendly"]', 3),

('amicable',
  (SELECT id FROM clusters WHERE name='interpersonal'),
  'Having a pleasant and friendly manner, especially in situations where tensions could rise.',
  'The two sides reached an amicable agreement that both teams could genuinely live with.',
  '["friendly", "cordial", "pleasant"]', 3),

('supportive',
  (SELECT id FROM clusters WHERE name='interpersonal'),
  'Offering encouragement and help to others, especially when they''re struggling.',
  'A supportive team member shows up in particular when a colleague is having a hard time.',
  '["helpful", "encouraging", "caring"]', 1),

('cooperative',
  (SELECT id FROM clusters WHERE name='interpersonal'),
  'Willing to work with others toward a shared goal rather than acting unilaterally.',
  'Cooperative problem-solving reaches better solutions faster than parallel working in silos.',
  '["joint", "collaborative", "mutual"]', 1),

('charitable',
  (SELECT id FROM clusters WHERE name='interpersonal'),
  'Giving others the benefit of the doubt rather than assuming the worst.',
  'A charitable reading of the email avoids the conflict that the worst-case interpretation would create.',
  '["generous", "forgiving", "benevolent"]', 2),

('deferential',
  (SELECT id FROM clusters WHERE name='interpersonal'),
  'Showing respect for someone''s experience or position by yielding to their judgment.',
  'A deferential attitude in the early days of a new role makes it far easier to actually learn.',
  '["respectful", "humble", "yielding"]', 3),

('patient',
  (SELECT id FROM clusters WHERE name='interpersonal'),
  'Able to wait calmly and tolerate difficulties without becoming frustrated.',
  'Patient negotiators consistently get better outcomes than those who push for a fast resolution.',
  '["calm", "tolerant", "unhurried"]', 1),

('warm',
  (SELECT id FROM clusters WHERE name='interpersonal'),
  'Friendly and affectionate in a way that makes people feel genuinely welcome.',
  'A warm welcome sets the tone for the entire relationship that follows.',
  '["friendly", "kind", "affectionate"]', 1),

('empowering',
  (SELECT id FROM clusters WHERE name='interpersonal'),
  'Giving others the confidence and authority to trust their own judgment.',
  'An empowering manager trusts the team to make decisions rather than requiring sign-off at every step.',
  '["enabling", "inspiring", "uplifting"]', 2),

('equitable',
  (SELECT id FROM clusters WHERE name='interpersonal'),
  'Treating everyone fairly and without favoritism.',
  'An equitable approach to feedback means everyone gets the same honest and honest assessment.',
  '["fair", "balanced", "just"]', 3),

('mediating',
  (SELECT id FROM clusters WHERE name='interpersonal'),
  'Helping opposing parties work through their differences toward common ground.',
  'His mediating role in the conflict prevented a split that would have cost the team months of progress.',
  '["arbitrating", "negotiating", "bridging"]', 2),

('discreet',
  (SELECT id FROM clusters WHERE name='interpersonal'),
  'Careful not to share private information or cause unnecessary embarrassment.',
  'A discreet colleague keeps sensitive conversations out of the open-plan floor.',
  '["private", "tactful", "careful"]', 2)

ON CONFLICT (word) DO NOTHING;
